import streamlit as st
import pandas as pd
import base64
from pathlib import Path

def procesar_excels_a_lisp(lista_archivos_excel):
    lineas_lisp = [
        ";; ==================================================",
        ";; SCRIPT AUTOLISP GENERADO AUTOMÁTICAMENTE",
        ";; ==================================================",
        "(defun c:DIBUJAR_PREDIOS ()",
        "  (setvar \"CMDECHO\" 0)",
        "  (command \"_LAYER\" \"_M\" \"PREDIOS_AUTOMATICOS\" \"_C\" \"3\" \"\" \"\")"
    ]

    total_procesados = 0

    for archivo in lista_archivos_excel:
        try:
            nombre_archivo = archivo.name
            nombre_predio = nombre_archivo.rsplit('.', 1)[0]

            df = pd.read_excel(archivo)

            # Extrae columnas D (Este) y E (Norte)
            col_este = df.iloc[:, 3]
            col_norte = df.iloc[:, 4]

            estes_limpios = pd.to_numeric(col_este, errors='coerce')
            nortes_limpios = pd.to_numeric(col_norte, errors='coerce')

            df_valido = pd.DataFrame({
                'E': estes_limpios,
                'N': nortes_limpios
            }).dropna()

            if len(df_valido) < 3:
                continue

            estes = df_valido['E'].tolist()
            nortes = df_valido['N'].tolist()

            lineas_lisp.append('  (command "_PLINE"')

            # Los vértices se dibujan respetando el orden ascendente de la tabla
            for e, n in zip(estes, nortes):
                lineas_lisp.append(f'    (list {e:.4f} {n:.4f})')

            lineas_lisp.append('    "_C")')

            centro_x = sum(estes) / len(estes)
            centro_y = sum(nortes) / len(nortes)

            lineas_lisp.append(
                f'  (command "_TEXT" "_J" "MC" '
                f'(list {centro_x:.4f} {centro_y:.4f}) 2.5 0 "{nombre_predio}")'
            )

            total_procesados += 1

        except Exception:
            continue

    lineas_lisp.append("  (setvar \"CMDECHO\" 1)")
    lineas_lisp.append(
        '  (princ "\\n¡Proceso completado! Polígonos generados con éxito.")'
    )
    lineas_lisp.append("  (princ)")
    lineas_lisp.append(")")

    return "\n".join(lineas_lisp), total_procesados


def cargar_gif_base64(ruta_gif):
    """Carga el GIF y lo convierte a Base64 para mostrarlo directamente en HTML."""
    ruta = Path(ruta_gif)

    if not ruta.exists():
        return None

    return base64.b64encode(ruta.read_bytes()).decode("utf-8")


# --- CONFIGURACIÓN DE LA PÁGINA ---
st.set_page_config(
    page_title="Generador LISP de Predios",
    page_icon="🏗️",
    layout="centered"
)

# GIF del encabezado
# El GIF transparente está incrustado para que Streamlit Cloud
# no dependa de un archivo externo.
GIF_BASE64 = "R0lGODlhoACgAIf/APn9+PTGBQMCAv7UCTU5Mbh4D+W4CbW6s8qaCVFXVBgWCGxYEfnQKKyEE0s4BPlGSiYaALCTHCslCtvh3JV5CM6KFtLXz3uBf6OppzwwCHB0bM6oBvHUUNiwFWRqZVVBB4+DRYRsGbmjRmdcMn9iD85/ED9GRklGLJOZkfPONiAmJsDGxc+2R+1NN/taR/alL6CkmtzDT8u5ZcDFvfiMNlNQNWFKBKycU8tqEMSrP29oSIl0MZh8TYCEeomOjPr9+aZ6JwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQJCAAAACwAAAAAoACgAAAI/wABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyhTqlzJsqXLlzBjypxJs6bNmzhz6tzJs6fPn0CDCh1KtKjRo0iTKl3KtKnTp1CjSp1KtarVq1izat3K1SeGBGDDrui6U4OAs2h9TLDAlqzNCwIo5ECAIIcDtATc1oQbYYBfDiQgSJBAQIOGCxom6H3JN0WAxwH8DkCAVsCBxS75MoDM2QCFzxQkCFAgwAPmlJo5c5Y84O7ZEwcwwFB8emRq1bg570CLorZtARFyC4+MYIFxAoRV5PXdEW6DzcNxM5B8ojKGGZeZZzSLgEP06AY2bP8wUANtdu0WMahY0OF79AGRG3wgfR59RQwCQMB3/31A+fr2TYSffvz191+A6eW3X4G5eVZDAhYgeJ+CrEnG4AA3CJCAhBbBIAABxoVoHAUDTBfZibkNIIIAJnBYEQqVxaiAAR3UaKMBDYJQmosUTXDAj0D+uEICMZ61wIKPsfAhjx/BQMCTUD5JQQycySCACkyadBYLCyq5XJYjnSXDfgPEMBqYJG25XwMnnHABmmEKMGYAHCxg2Q8T5AnnR2I+loINMWK550YHeCAmfCmElsGiZxmmQYSDWmTolqtJRpp5kVoEFwg4CtcABSCIBmCmEJkFwnsDcHDXqBgpRluAk0L/EEOFFgYQw6odXXoWpOgdQKQCIYRAQbDDBoujqpZxNEGMHqDgQw8YaGdBkTFuUOZdY220LLVLaocCCjCEK+4BohVA2ZcVzaCACioIoMEPvlZGQANsZqDChhKSm0EBBbB4kQVm4XXACpOepYNfdl6J3QwBCgBBAyX0m1eer0JEJLeV3bCfASmEgFbDEPBQQQEfQFAZqwb1EOUJBFCbQcICSLBACn4xUBwJJzgQrXYO71AADhXYqQBpKFRckAUzWGBCZQs0QG0IAVQGgQgIjBcZhhpOkLRvaGVQQQklfD1ytwe1LMAHQPDLbwUviFYZCRxsUKMBOp6FQM0GGOB2i7WF/5UBAQ4E/rLEB1mQAOAOkAB2ARFXwAAJDpxwKQmOwTcACx84kMEHC9jQ1wAhOPABARAyd3HXQJBNEIwj+DVyA2pXcHWdZ8Gtml9RGxxAp7TvXJsFP84AowMV7OCaANm2G0F7AVQAe+ycFdCuAhL0hRsCEURgMsYaMjctBCfgQMJoH4IFgQMBQDcy42tz9gLMJHRaKQfzKQCBYPgLRn0CJhzuO1krQAsJvlYCHqCFAt6BDALUBjvZKZBflyIAknIDHdVwIAKVMY0FjKaVb/UALfYjgbnk95jXQe+BFbCBBD4ggaF9gAO4Y5Dc5HYpfOlFBbriAQJyQ5cCQKwADnzMAv8ZVwIOUOAsGWhA9kjYH8ksYFE1SAxmtiUy4RjAh+17IBY7hTW71apAkjkiyrSyrQYwb3ePwVEH1OZD+Q2RX/LrQIgI4wDrMSiNOrIhWaa1ACpZkS6A5EwHKgBIEuLuAxkQwAjuCJnLqa4rFpDABIczyfShKgcCyEACL7QidHGlBydYACNHaasFUG6UDjpBtrjSMhmQkpSV5M8AdCAAGJBlaSKI5St3SUk7/U8rLcslL4dJSdwNYAQC+GVWgqlLYr4yPDWKDDKViRVmOvOa0jyLArJJzatYE5vEPGb5uEmWb4KTl+L8wQ8i48tyCkCY52RkBbN5Ag+QsyvmjKd7DPD/ghfIT5yjuScr39lM4cxzlwNwQQta4IIFLTCg4hxjVVpZUNzkjYmjfAENFMpQtgmxACFogBBJkAANJKA3wBTADRhpALTop6LCoQEOHkDTBzB0MwgQKZkGgJetrABGL2SQAT6AyA+EgD13TMELSlBTm9LUBTh4gXAQcES+bUUADtikLAeAybM8h0EMeMFMadqCpuKABgd9zABaegKuLCuoLKUXBSCQAQYpdaxPrelZ0xqAFHTgkVdZVlZhWaKA3tEANChrTRmaIu1JAAIa6CZVlmUDP5KypRDIKFOfWgEaTHIAdRMAB7NCJGu90mGw5GhD39MyXnHlAgqIwA5JiVpS/9KABp2lJAUcYAIPjFYr7ULRHWv7SgbwdXfk2RFmLgC4EMCUMw47LkIdmazaLEsCo7xf3rBpgOyBAAJ6PI3hVMoa9xhRADWI4e0qyhrKnMWqzIEtAWxgA6O6hwKAksCwzhgZFjigsrRiDQNCkAHNfUADHmgWgiojAenurkhfxeNZbiCeClt4A3bpqYtWYAH8ZIA1dxmaiBXQtM98Sn4s2B730rKWDWZpWtWjVwPcFqPPfTEAKf5Q4N7Lv7D0jwAMg1MAY/QmghgqAo7BTZkcBkOeKoBUBwnSj1wLALNEIK0M2IAETnA3EfzNB1CWyJHTmgLKHGwDuwlvmBtiZTJTZrEBVlIBBla5ZoeMGTcO0O8GrATfOjukzbghzWYypGY/L+TISW4kaWhHZ0OzGThIMgACMiABEdzlt45GiKHkwkUdNWBFpsk0RITXsgZIxtOY1ICoJbI0EohAtsgkgY6KvGqH4Id7oa51QwB2gV73+jC/lqiuh03sYhv72MhOtrKXzexmO/vZ0I62tKdN7Wpb+9rYzra2t83tbnv72+AOt7jHTe5ym/vc6E63utfN7nYPOyAAIfkECQkAAAAsFAAbAGwAWgCH+f349MYFAwIC/tQJNTkwuXgP5bgJtbqzypsIUVdUGRYIbFgR+dAoJxoA+UZLSzgEsJMcLCUJq4QT2+HclXkIzYoX0tfPo6mne4F/cHRszqgG2LAVPDAI8dRRZGplP0ZGVUEHj4NFhGwZuaNGzn8QZ1wyf2IP8842ICYmlJmSSUYswMbF7U03z7ZH9qUvYUoE3MNP+1pHoKSay7llwMW9+Iw2U1A1rJxTy2oQxKs/iY6Mb2hIiXQxmHxNgIR6+v35pnonAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACP8ALyQYSHAFgIMIEypcyLChw4cQI0p0mEGAxYs6JljYOLGjx48gPWIQQCEHAgQ5HlwkELKly5cTR0IYQLODiQYRIhDIkAFDhgkwgwoNKfNEgKMBaA5AcFHAgaFQoz6UyQCpVQMUslKIIECBAA9Sw0alatWq0gEqLRI4cOGCBbFwW5ItSxcpAx4XU8TdK1IAhLqAkyJYQJiAThQs+SpmOFJC1cB0GSgF0fQCjaeLM1dE0AEy5A0aNBiwcRFzZr4XUCzY4Dmw5KQSQHg1fXrvBQEhBrRuPYA07dpwb+fe7bm3U+CocesmDhirjQRvkccVfvYs8wE3BCSQzleGAAKEwxP/pjDgte7ldAeMEPCB+94UTeMrMLChvn0DdQ2E+Oo+7oQDAAYI4AoJxGfRAugd1cJ3/XEnAwEQRgghBTBYNYMAKDSoIUIWtYDegolt2KBFMyw3AAxdiahhh7qdIIEKKmCg4ogClBjACQs49cMEPM4oHYlHdfBCfBn6eNoBHpDY4lYcNGkRTxlEZ2RcSXZollJelTblXiOFgB9gElAQAle/bRlVRSFAVpNKZQYFFFBTVtkADNUpdRQMbEqVpUVSqnhAgQqIIAIFghIqKH4d5AnVBPF5kIIOPlygogUGxqfBiSoZtGilFrWnYgopyCDqqAdwVQBTIbpEgwIooCBABj/8/9kUARK8GAEK221ZKgcFFMAeTBZUtNIBK1Rp0Q405YjhZTQYKUADEpDgK0s8wvlRgZw2dQN6J4hwkbMN9FBBASA00FSbC/kgoQoEVMqBsgJEsMAJNDEwmAkqPCCpis/yUAAOFeSogFcpWLuQBTRY8EFTC0hQqQgBNNXACAiIlhR22k2Q8IYXcVABCSR8PC6DDbUrAAhA9NprBS5w1ZQJHdy3n0UI1GuAAS572iBBHBDwwM/vTsuQBQn4/IAJIBcgbQUMmPCAClmaYNRRA7QAwgMcgLDACzMNIMIDIBAAnYjYdgwEyQrBVwJN46pcQAUXd6CsCQleHPGxAXwptwD7av9oAYA0wPdABTykJYCmrkLAWgDjSqAy3EgV4KoCESDwmFUIQACBudlqJyKlDaiAgwldfTdQAw8E8Ni40q5slQvwmvDllR3IpkADuEfQwO27R5DAB0X3jdwKF5nwMQk9XERBZ0hV4PjjmPeaJQF113U5Uh1A0BRYFhh8Gqg+XHS7CafOflTj0COFgNIvRABCBAOD0AFNzAWgAWgbZJkrdyjs2QMCdTlJAaL1tugpjQQdoIBFIqA5CJivOEpZQJNs8JP+MEoA4mrOAF2nvl457ksYo5mdrkMTBaIrMxeUwOLww8IAbMBtFZjd+lQ2uw2ERycPmEn9jqIfz3GHUguoUHP/TkJEq2igAkQ0H/1AwAEBlGCHVAOReywQgeoBxopWRApNciAADjDvOutJVW18oIIFQBGKMHiB1KDoHBVoqjbtmsEZoUi/Mw5gBwKQAXIWNoIszvGPgRlAjoSXmXb1EZCIDCT9BlACviHHkH5M5BwNcD/WMNKRwIGkJDeZlEZ2pZOYhKMADsnJRF5SbKAk5GI0WUpEXvIHP0jKIB85yki2EjDXu6QKPJBKWpLylrsxgAtcMLtLfvKSqlQMK+t3vT8OIAYsYEEM0LO+YzbyhHFZmI3qd7MHQtEFNYCmNFl2lPWJQALlNEECMpAAHZymXTfYoQEukhtbBqYGOHCAPh0g/82qIACdJhrASk6zAvjIjzkGeAETQSCC1dTvBC4gwT75qc8Y4MAFgEGAAnWWGQE84Iu72eJFHMMcBrggnxNlgT5xUINmUm2eKqgNow4qz1pRoAEcYA5EUUrRfbLUpTfaANoWw6iP2rE8n+RmDVS6T2nWZQCb010GkukfAbxAiGecZwN2aFKJVrQCNajeAGYmAO9lpkCXmuOz7CjOaaqpXX06DQYUAAEAnnGtZ6wBWGsQSAo84AMeMOtpXJUUKOKVjlUBat5Gw5/+YMBnIrBnWZ6lWGdWzSLYPA2jIgBF3N2MkwbQXAgasD8NTWBh2xohZBIoABvUsSyvVSRNmNIpH//NlQAvUCjEPEOBIUWAUIuL4gOuWqezMEAEHMAaCDLgAUdNqSkRqGzeDERSHs7sBqHJrnY1kJKBmgkAK7DAbThwFpUM7LwKaFhWwjS7FnCucxjRCEe+exBKMbBWEnBZfLqm2gC49zs/69TvCAI8AjSLvgohXnxklJAkQWBqsEVRA+YnUAUg2CMCAlBcKwIBl55AAxFQQc1G0DN3XngoDvYwU5ClAbyU9sQw4bBL7SWABVwIBRd4I4xhkmK6GIYCGrgQR3ccY7+41CtVyc6LiewSB0OYaubam46Z/BIOJ8gACOBABEagEsFSGSRJKgkI9yOB9YDly0IJXLskoBQyczElA2iGysJMMIK6NtIE+2FwnGFym86dec8vCRYGBj3onhQ6syEJCAAh+QQJCAAAACwLACQAdABRAIf5/fj0xgUCAgP+0wkyNS1SWFXT2M8WFgzmuQqWewknGgDJmgouJgj4Rkm5eBDb4dw8MAi0urNjamc/RkaRlo0gJiashBP50ChhSgTPixjOqAbz1U5rVw/xqSejqafcw0+JjoywkxxLOAR7gX+EbBnYsBXzzjZVQQd/Yg+5o0aJdDGViUiAhHqsnFPAxsVwdG3OfxDLuWXtTTdJRizEqz/7WkdvaEhTUDWYfE2gpJrAxb34jDZnXDLLahDPtkemeieknXLl6+f5/fgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/wALCBBAAYDBgwgTKlzIsKHDhxAjSlwoUECBHBQygnAxsaPHjyBDAiAwsGTJFyJTqlzZcSCJBDBjEmBQoaYBljhzqhSgYMOAn0BFmKSgI4JRnUiTOuT5IYDTpwiiBkhhUoDSq1gBMH3K1emADyg4iD0xoUCBGSCyqt2poGnXrkAHhDA54YGBm2vzTtz6tm8ABBoCazgwkIDewxD5+n0blwMEAYYRS16oeLHfAQEgT96MsLLlvgg0c+bs+XPX0JFHTy5tGqrowyDMyh4hmWeM1n1NoJZM0mSFB8CBrx3oM67xz7sRP6hYtWTqqyMkEBBBvTp1CCSM/+SaHLEHAoRNHv9gwAACBRAZI1xtbpJAicDvAyNw/Rwx84EYTGxIYFLC1bsABvgAC+y1cEEAur0mWQ73YeBTCTFZAMEBB/inlw5l3WBWBQKEgNlfCv5nF3AG2BWEASad4EMJCMSFwUAMvCABC5O9IEALmB0oAANq9cbejwwAdQFmG5ww0AGTSXDjTyQoUEBBWSn5I0/kQUBelRBkKQIDCwSwgAYrhKiWkjgOMIMAHK01wpQLbBDAT0PyV9UJMFnAwUAsaJQRBSzkoBSZb56p3loeFMBhcwscyF0JjLI415RVIZkUmT8lcAIBNWVaAQF4IXVfSRbMB9d2mCVggQoD2RDTqjCRQFgBOlH/GsCQQjXXqU4RjEBBeCVBMICilw0Qw0AxaAcUAgwoMEMEt6YkK3d/BUDSA1m9QMC1EwyEwgIfWrZACKIGGyasLD3L2GPNZtWbCt0utt1nA9DAAQETlLukXxc8Rm2PAvDarwAJxIXbZUJ5sK9ISlKoMIUKcPATujmVOKLEBjDQ78KEMXDDCRhgQEO7AzuFwFz1prRmeP4SgNm0OHkw5Qogv2lxSStEG/JTA4Q2g1IuCABBBhkoIEC6HXnggVEvQHCCleQpkOwPMQegwQJUhzlQAsCGXIKYLKFIAAwWCH3wRw9UtV0GMKQNQwbc9jXkTx9syUAIIQscwouD5tQzBGBb/8ysgBAZUNYMSouFglMdWODA4ot3aRpQN1tAAgldbkCCAB4g1TMBaKPaHLkOUVCSCh1AHkDiijPe9s2tfSC0APmZgALmmvsMgwM/yF2e0KAzZCMHqnN1QQcZLA62A46zbtoHNIGgQQAbzJ65TnujDfT1GaDau0IRFKCA8ch3lbgDiiuevPKWbaAAAUJs8EH0tFM/kAL080S/AzZY1FDZ3zPuQAaimg/x/Be+aM3ngDYTWchc5xITyC5+EbtWpjCVKhzobyERYAABEsC2BQDtfE+ZGtUyUAL0tQYFJOGAAy83vTEJgAQW3N5BQCAAmD1lSJ/JmglvqMMFWDB2s8tbVv8EYoMYLkSDGijhDneIgB10oANcKd4CRLUAFNjALEKclABQYMEJROBoRvnijnS4RNYtoAEN6EEHFOXBWXllAy8SAI2wQkSg3ak5FijjEmtQAzTKoAYghAuq0oIVJRGgYz5SAA/CogEy6rE1T6yBDNCIRjW6a5BD/FFP3vVI1kmSkqBsABT7MgBMYkUHFMDInijgAdGpsJPK+6QfKSmDUY4qTIREjAFcaQJYevKPoZykLbkSgrsJIJeHIUkKfIm+DkyyAc+EwTBdU5I5IiZbKYgaM02zg0/KYAeBfEqTLKKDyWBTm9v8TAcqWbrFFEkAYzvMOdPJug7swInu0oAAJuD/p83Mk543u4AjnxKCyyFTMv8EqB5/MhDVACChCiUlOt/0EwuQhwBQGg1EI9oVyYXrLSVYgLwGIkNzCiCbHCUlSUpgrJ8YSX8lcuhDTzpRepogBIQRQcc4hgGeYkBD/JTpQTaa0gvMDlIEEWpCslWslL4FASkQygqmRoPLScAAEYinUCXAgKk69S0buFM2fzKXgyoVIRy6TSdb6pd3AsEpJrCAHM/KEA59oKYh0wCrLJCA5/VlATY4AAagNxfa0FUhhKGB8jjplVKyhwRuYsywINAU/hj2sAh5wJqyc7Nv3VADHEDBDXAwAhaYtrRZehNcaOAzOB4TswtxQQVOoIKP/35mWAJQqwnkVIGFkMQCSsTZZDdwg6HBliErDVkCfCSAZR2NIS6bAciGK5Q0HTchJFEtbgbQgoFwyEINMYB0PNYt1vaLAAUg2nEFkoBwXiZM4I2IQHD0FPNe8LqxhQxevQLfjvzzK/1ygXrxOyAJKCBgjwsTSiZiLQKoaAAauMEMWojfhrhsg7ZlTHfjKxEO+eAC/DFrhZGb24kiwJQdOVR4KDzihmRrPApgKVd+ElYBZFEiL1ZYOVv8kGyVhHJc0YAF7DQB6/JYXQL4gNUq8KEB8ICkR9aLBCBgAw5ggEI4e/J9ozwcAWzgMUosJf1uAIIdczkrEZCSbYwzlwWfGSfNFxOACkJgATqHYHYFuPGblRIBpA54zzh5wAtGQOjSDnoEg1ZNQAAAIfkECQgAAAAsCwAkAHQAUQCH+f349MYFAgID/tMJMjUtUlhV09jP5rkKFhYMJxoAypoKlnoJ+EZJLiYHuXgQ2+HcPDAItLqzY2pnICYmkpeNq4QTP0ZGYUoEzqgG+dAo89VOa1cQz4sY8akniY6Mo6mn3MNPsJMce4F/hGwZSzgE2LAV8842VUEHuaNGf2IPlIhIrJxTy7llwMbFcHRtiXQxgIR6zn8Q7U03SUYsb2hIxKs/+1pHU1A1mHxNoKSawMW9+Iw2pnony2oQZ1wypJ1yz7ZH5evn+f34AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACP8ACwgQQAGAwYMIEypcyLChw4cQI0pcKFBAgRwUMnpoMbGjx48gQwIgMLBkSRciU6pc2XHgiAUwYxJoMKGmAZY4c6oUkEDDgJ9ASZikoCOCUZ1IkzrkCSKA06cHogZAYVKA0qtYATB9ytXpABApNog9YaFAgRkesqrdmaBp165AB4QwaeGBgZtr807c+rZvgAMYAmNAMJCA3sMQ+fp9G3cDBAGGEUteqHix3wEBIE/ejLCy5b4HNHPm7Plz19CRR08ubRqq6MMezMoWIZkni9Z9TaCWTNLkhAfAga8d6DOu8c+7ET+oWLVk6qsiJBAgQb06dQgjjP/kmhzxBwKETSL/aNAAAgUP5yNcbW6SQInA7wMfcP0cMfOBF0xoWGBSwtW7AAb4AAzsrZBBALq9JlkO913gUwkxVQABAgj4p5cOZd1g1gQChIDZXwr+ZxdwBtgVhAEmnQBECQfEdcFADbggAQyTuSDACpgdKEADavXG3o8NAJUBZhqcMBACk0lw408jJFBAQVkp+SNP5EFAXgMJQKAlBCQ0oEAACmCgQohqKYnjADMIwNFaIkypgAYB/DQkf1WdAFMFGwyEXkbnUQBDDkqZGWea6q31QQEcNqfAgdyV4CiLc01ZFZJJmfnTAicQUNOmExCAF1L3lVTBfHBth9kCFbwwEA0xtQrTCIQV/6CTpQEMKVRzn+oUgQgUhFcSBAMwetkALAzEgnZAHYDlDBHkmhKt3P0VAEkPZOUCAdj2loICH1qmQAikDjumrCxBy9hjzmbVmwrdLrbdZwPUsAEBM5S7pF8ZPFZtjwL42q8AC8SF22UkfbCvSEpSqDCFCWzwE7o5lTiixAY00O/ChDVwwwkXXFBDuwM7dcBcFqjUZnj+EoAZtTh9MCW7jFlckgrShvzUAKHVm1QLAkDAAQcJCJBuRx98YJQLEJxgJXkJYMkDyE5hoMDUYw60gLAhl0AmSygSEEMFQR/80QNVbcdBDGjHwAG3fQ35EwhdNhBCyAKH8GKhOfEMwdcWN/8rIEQGlDVD0mKl4FQHFTiguOJfmgaUzRWMMMKXGowgwAdI8UzA2ao2R65DFJT0QgePB4B44ouzbXNrIAQtQH4mpHB55j3H4AAPcZcX9OcM2bhB6lxl0AEHin/tQOOrmwYCTR5gEIAGsmOuk95n/2w9B6ryrlAEBSRQ/PFdIe5A4okjn7xlGiRAgBAagAD97NMPlMD8PM3vAA0WNUS294s7wAGp8xle/8AnLakUMFoDa51LTBA7+EUMW5vS1KpwkL+FRKABBFjA2hTwM/M9RWpTm9r5WpMCkmyAgZaTXpkEMAIKau8gHhAAzG5mmRyN8C0ZwBqYKAg72eEtKwKhgQv/F4JBDJTghkg8wA460AGuEE8BpFJACmhglh9WSgApoKAFImA0o3BxRzpE4uoUwAAG9KADjOJgrbyigRcJgEZYCeLP8tScCogRiTawQRllYAMPwkVVacGKkgjQMR8lwAdhwUAY79gaJtpABmUs4xndBUgg/qgn72Lk6h4ZyU4yoIl9GUAlsaIDCmCETxT4QOhOqMnkcXKPkZQBKEs1pkAixgCrNEErN8lHT0JyllwJgd0EYMvDkAQFuzxfByDJAGbGAJiuKQkcEWMBAaAAaslszQ44KYMd+PEpTbKIDiZTzWtmM3kdkCTpFlMkAYjtMOXE5jk/04EdLNFdGBCABQC1/5l4znN1ObRMCCxXTMn485+M/MlAVAOAgyJ0WDX8SQXIQwAojcahD31L5ML1lhIoQF4DeSE5rSnPhw6AJCVA1k+MlL8SMbShJM3oW0wQAsKQoGMcu0BOL6Chfb70IBiVaa1kJymC/DQh1TyWUE+DAqGoQGo1sJwEDBCBd/5UAg146lK7ooE8XfMncynoURHCIaUmFFl+aecPnGKCCrxxrAzhEAhKujoMuKoCC3BeXxRAAwRc4HlzoQ1cFUKYGiQvk14RJXtGACfGFAsCTeGPYAeLkAe0KTs2+9ZTMoCBDaTgBjgQAQxGK1otxQkuNehZG4lJ2YW0YAIneAFHP1MsAf/cBkF0msBCSFKBI3KFWKq9gdBayxCUhmwBPhIAs4zGEJfNAGSP1YBQ1kTchJDktLgZwAoGwiELNcQA0vFYt1LbLwIUYGjEFcgCvnmZMXk3IgLB0VPIW8HquhYydP2tezty0K/0qwXote+AJJCACuQ3TmNCyUSuRYATtAgDN5iBCu3bEJdlcLaM2e57JVLWDPCAtRSOCEnM6pcDjLIjiSrJhEPckGqOJwEp/e0AuioAK0rExQobJ4sfUs2STI4rGKgAnixA3R2rSwAgqNoEPjQAH4TUyHqRAARosIELUOhm+KsvlIcjAA08xreiTAACbuABHW85KxGQkm2MMxcFnxknzRcTwAtCUAE6hyBPBbDxm5USgaIGeM84eYALREBo0Q5aBINWTUAAACH5BAkJAAAALBAAIQB8AFQAh/n9+PTGBQEBAv7TCcabCDM2Lrl4DxgWCM/V0GtWD5GWjeW4CUs4BFRbWGRqZZR4B6uEE/hGSrW6sywlCrCTHM5/EG90b1VBB9vh3KOppPnQKCUZAPHUUs6oBjwwCPPONklGLNKJF2FKBNiwFfGpJ3uBf1NQNYRsGYmOjMDGxcDFvYl0MaCkmiAmJj9GRmdcMu1NN5OHR9zDT/taR29oSH9iD6ycU8SrP5h8TYCEes+2R/iMNqZ6J7mjRstqEOXr5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj/ABEUGDgQA4CDCBMqXMiwocOHECNKnBgRgYCLFxFQ3Mixo8ePFQV4uDGCwoGTAlyAXMmyJUuLDDgMWHDygIAJLBTkVOGyp8+fB2HKCECU6AAaGAU0AMq0aUeYHIoaJfCg6goGBAukcMq1a0KoUo0OGMtBRFIFCCSo4Om1rU+hYeMumLtgRFIBbvO2BBs37gANARhM8DBhgs4MehNz5Nu3MeABMTAqniwRbuPLREc8WCHigALKoBkyxtx4LAQBJUKrRmiZ9OUPD1BTzlDAhQsQtgtYmDzadVzYAlBQLnH3omcFyJPnYNsUwQEGN3xf5hA79WQFxbNjXIoAg0amFgQQ//ggPeyABBssbHUroYEDBxYKaBew4gGEqvZtYtwNNDwFwOUVNYB8BuWFwnx3xdABAQwyeIEHHgj2ggRq+RQeAWNlqOGGGQoIggDftdVAC9klQAAFFESmXQ0aypeShSKBwMAFM9ZI4401rjDWVTaF6NV8J+gQwAAfnCBCAkgmmYAHIFwAgggnIFmACS440FJ4CGYHwlgmYOSjVyzMR4BYHA7gQVI9DPnhRQZhUGBHGKSAwJx01kmnChhgZ8JYLwSnGAYuNOBiUh1EddkIHSRqg34PLCDDCUlZ11UKAojAp1IlwKepBQ181pUExT3QAWkZynBBYRckUEMCF7SKlQUWaP+KGFAZCLDlAF3OV4BXGGQgwYEYTdAhqX9hdOsAARS31E/E1RBdAARAAAEF005LQWy75gWfBTY9eIIGY7lGLQQEABjAuNYWYNOyLTkgHrJDlgmtANkmNqgHOowwgmsaSsVhAhcVoABzIPlHXmldKvCmXnUCK8ACGwb4GwUCWMmSuxjKq6YA64WGQAMNuLBBYSRDLHFRGlDM30rhPXBDogTAPObGEqhGoVrY3SXCAycTpcFpFq/UAII2jGVWx5TdRddcBAjQArwnLxADAyCulAHIDmDtHok9LPCAfDXnlWdyyJmAJJRSAUZuz0VxcEHVTA3dgw0Yhe0WpXfpOKy/UPf/zMGZC/s0NA4rpDTrWy1kpfgENNyHXwfmss13uEQ90MIBLMRNX+ENpHXzzYd3BCqCN3AouV8UqMqzUZFJ2lMKLgiAQ58Ihv6Qwxh1QJcBvPcewun85iqAgJEJ5xOlE/TOwPLMMz+BALYrRLYJB2xg/cgLHFwBBNtXYMDMwF82QJ8ZqEC8bMfT670BFbRfQQjthxACwNEjpEJSEwAYOVEQ9M47+OHry/hA9IPzGe919JJf/N7nvhVsoAUKa0gDDgCCJJ0AM/3r3/8CKL5cHUBAhTugSyh1gFaZ0EYGwAG9GJID+NiEBwoEYFy2x74NclCAPDDLB1nnARe4jiX3Q9AL/1RYL4RgACMFoKENG5PBGsqQg/ojAQEmsAHz2OQnLMiAFrfoq6HVgIgKOVANKMC77WmQXCRozPp8d8OiLGAGO6gACUjwvQXE5XkC8wpxaMCDByoABX9UwIcIEBUN+u97bgyAHRdwSAOEYC6KDOAcIxABGOwgWna840XY5RTivKB9+sFIAtzYIAKEoEFp7MsCFsSgU7ZxADOAASUp6QMS9K0oIzBAxfQoABrALwEiuEAwT3BLqN2yNEZpIwlCEMtZVvKS5hmLXYLWSQG8oHfuk2Mb29jMWcJgBpT8nVRGIC1IUbMpWEpKHTO5zfDBUpaUBOcsQ0ACAB0lKZxsigIO0P+Cfl7uAjzYXzslp4EdMNOZlZxBKqeiwwbU71O2mslAAwiYbtLSlmEBzAp5E1F2TrQ8lJPKHGVpycssYKOJUUADJnDBj57sRB4lCglkWctjZsZWk5HPkFwqsQEJYAT98g1kdjmZD8WUp/yCQAKWR6MEfCCk0QzAA0xgArvZ62FI7elJMbKBHiRKlR0YAd0OEBr5jOBgWS0PzEZAu+FtiAMAuwjSEpMBB9BoAQJNK2Y0RIEIFUBJSYJQATwAq3O6ZWgY0uvpwqWdIdHtIgqYq1cwhlbFSo5BKhLAA3QwlgVQIGZs0gtiK2vZno1FBx7YwAEScJ9yDYCcBdELZUvbRoz/0GBH6BOteEir2DLZFINVEYFwTeCBh3JltrSFFoo+iyICHHWvA+DA85RCmdH2NkMc2EB2ZBBU18jgTBn4krZ2q1jHbeYE70mvAxhAA/xQQDrfxQtorPtRDoUSbglJ501+G5bsCiBwsiXvNjO0AMCKoAE5QQ5DVJAcFkxQtRCuXk2qp1oTeKq6Ar6hvsJKsbtcWCI5yNJZVENf03LIvxiJ7OcAvJqeuOs/kqPACWb8gBM8oAYeyIp4W8wUQYonr5gBEAeoVhwR8tgrvYHuACAwMtWCIAMsiHIW0XJkr0jgAAVg3BMx04HPCk8AK6uyXsJ0Ee4KNbpxJauYQwOqF0zuj5hjWVKOY2XkNcu2ACKAANTwI8NVLmC6+bSzYgRwgL8QZZX70RBcL9IC77BY0HlRrYC65AAU5OBIgM1aDiC9mpMQRQcJiC0AivNDToPG0wGgGydVcDNWP9rUifH0AG5AXVhz2tMUeMEBDGvrKqtWuv/t9a0PMORgC1vQhbHB81597NXkzNjNXvPH4BPtlQQEACH5BAkIAAAALBAAIQB8AFQAh/n9+PTHBQEBAv7UCcebCBgWCDM2L7p4EGtWD8/V0JCWjea4Cks4BFRaWGRqZa2EE5R4B7W6s/hGSiwlCnB0b7CTHM5/EPnQKFVBB9vh3DwwCPHUUiUZAKOppNiwFdOJF86oBvPONklGLHuBf2FKBIRsGaCkmvGpJ1NQNcDGxYl0MSAmJomOjMDFvT9GRu1NN5OHR9zDT/taR2dcMn9iD29oSMSrP6ycU5h8TYCEeviMNqZ6J7mjRstqEM+2R6SdcuXr5wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj/ABMYGDgwA4CDCBMqXMiwocOHECNKnBgxgYCLFxNQ3Mixo8ePFQVosOGhQoGTAlyAXMmyJUuLDDYMWHDy5AQFJkwoaOGyp8+fB2HGCECU6IAaGAU0AMq0aUeYG4oaJQABQgkVDAiu0Oi0q1eEUKUaHUB2A4mkChJEaMHzq1ufQsXKXUB3gYekAt7qbRlWrtwBRBlM0DDhpokOexNz7Ou38YUAA2BgVExZYtzGmIl6gKACQQEFlUMzZJy5MdkHAkaIXg1WAIOhpTOHgJC6cgcDLlyIyG2AAmXSseXOFsCi8gi8Fz8rWM48R9umCQowsBEc8wbaqikrQM4d49IEGbgC/6UggECI6mIHIODgIIXeCA0cOKBgoLsAFVXzPyiQ1Pd4ARU8hl5RA9SXGAv24QUDCAQ0SIANGGiggWAzRLCWT+QRQNaGHHa4IYEiCCDeVw2swB0CBFRQgWTd0cBhfSlhKJIIDGBQ44025nijCmRhxd+IXtlXgg+QhVACCQgkqSQCGoiAgQgklJCkASjE1xJ5CXInAlkoYASkVybYR8BYHg6gQVI8QBbiRQZlYJBHGaSQwJx01klnCxlsh8AF6hGnWAYuNABjUiBEhZkHICR6A38CQLBADCUklZ1XKQiAAlkzKDXCfJxS0ABoXkWAHAQgZMYnWTFgUBgGSmLgalYUUP/AKWJAdSDAlgN0aZ8BX2XQQQQIYjTBh7ENcAFGuAKG3FI/HUcDdQEQ8MADFVBLbQW08arXfBTwF2EJp8ZW7QMECBjAuNcawB+zLTlQHmCQlRmtANomNqgGPnjgQbHEkrkhAhcZsNOVAJ5nWpcKvJlYncEKsECHA8p1QQUCOECwhvKqKYB7qyXQQAMucFDYyA9HXNTEAvi3krsQ2JAoAS+PqXEEq1m41nZ4kQCByURdgJrFLLlr3w1kncVxaHjVRRcBAqwAr8kLwMCAiCuZ8LEDV8dnIg8LQFAfzXrlydxyKCAZpVQXLEAuz0VtgAHVTDUgAA83YAT2W5XixWO/BD7/zfMGZyr8k9w4qJASrXCtQNDiA01QwwP5keo3232TVRQEKxRgQtz3Gd6AWjbbjHhHoiZoA8SU/1UBAjTsbJRkk/aUggsC4EBDlqM/1DBGINR1wO/Af5B6sboKQKBkxflUqQa/Y8XA89A/P4EAuSs0NgoFcKC9yAsYbMED31twgMzDYzZAph20cHxtytMr/gEWxG/BB/F/8AHA1SPUQlITCGhuUQ8AXgDJVz6/nE9EQFhf8mRHL/vN74EPVAEHVpCwhjSgACJQUgky8z3gja+A5tNVAQhkuAW6pFIFeJUKn3cAHNCLITmYD3924EACyiWA4PudDUFIoB2cZYSv04AL/2LHkv0laAYurBdCMoARA3RQhxzEIRR5eLKenYAA2ksPB/Lik8N04ItghI8AaJBEhSCIBhX4XQdxSIAFNCaAHhQeFQOwABnowAInOMH43CiW6QnsK8epwQ4mqAAWFFIBLiiAhgIARw9+kI5EceMCHHmAB0gSksPLowQk8AIdSIuPfbwIu5xynBnEj1EYQUBRFkCADzjIQSdojF1c2codpm4AMnjBJjfZgxNMTjO0URkpBVAD+iGABBhAZgkm97T/mc8oVDzBB3K5S0568i8DuAvQulJK4MkPj3PkITV3+QIZbFKORfHAtCK1TadgKSl7BGU4bzlOCZhzlx84gYCOkv+UUTZFAQVYgUAzh4EdOHOebLuADqZZTU7KIJYEIsAPG5C/UN1qJggtH5/qKYFeMjMAL/zNReWZ0eBYTix51GUnGxOCBYQ0MQpowAQ2WNKIpYikATiBLj3amLuIgDL1gUxNB1QgAXiAQ9WJTMUqEyKcDrU0D0DA82yEgBCcFJsBgAAKUHA3eznMYE81qUsxwgEegGBfczlr3Qogmvp44KBhzQyDCOCBTF0kXhvawO0ucjTFmMABEXJqXM23oQpIiAFLUhJhJBSrdupFbgQw1GB5Zrnu8KluF1FAX93iLvNMdngNYlGjjpq2BoGATXuBLFg/S9kB+EADHCgAAiBXrmz/PqAge+nsalk7PIzUoEfsS215djvYMv0SqlUhAZJQYIDNJUa3vI2WiiqQIuoK1jQD2MD0lFIZ1RY3r1tETgyQGpwYnKkDX3oLdOMKuaqooATyia8DGFCD/FSgOublYneHW1IPoRJuCXmnAIYVnA1sUXDP5e8cN7SAxJKgATpZDkNawByrZe/CsY1tTbRXABSAar+epaK+ekcxvHxYIjnIElpW4122lUm7aElB6BDMGp+4K0CUqwANSmAVq5RAA4tLb42BooAQlStiAtrA1JBDxCFTyjWS5dcAHiCy2IqgAznJSQfS4uSvRKAABnCcLTEDAnIVL2VdpkyYLjJek2YXmWACYGuaRSOqS1Xul2RhEpBldeI5P9cAJHjA0/JjwwX0brv+9LNiLmKsSJ72IhTg0AbgvILw0FjRezkJgQDmABbkAEmJxVoOMM0aTQfAAwjALQCYTOoha3oAP+Cu/kIXgUu3WjGvtoGsb41pTVdgBgVwLK/TfBIY23rYri6AkgVwbGSzpjA3mF6znb0anDGb2or22HywvZKAAAAh+QQJCAAAACwaABoAcABcAIf5/fj0xgUCAQL+1Aq8ehHluAnR18/InAc2OTGjqaORdAOTmJGEbBksJQrOixdRWFVtWRP50Cjb4dwYFgmViUgoGwD5Rkq0urSvgxNhSgRVQQfOfxDz1U1/Yg9LOARlamOsnFMgJibvqiQ8MAg/RkbAxb1vdHGwkxztTTfYsBVJRixTUDXOqAbzzjaAhHr4jDa5o0bcw0/AxsV7gX+gpJqJjoz7WkdnXDJvaEjLahCJdDHPtkeknXLEqz/LuWWmeifl6+eYfE3///4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI/wBdkCBhAoDBgwgTKlzIsKHDhxAjSjyIQICAEAAMSNgoYaLHjyBDflwhgEIDiygRiFzJsqVHFQJgQKjQoGaDCghyIiCBoITLn0BFPhBwIEKAAQMCcFCAEqULAyVKdAxKtapCEkSNBti6NUWKAl8xNP1gtaxVrCe4qkXKNoWGtxpWmPjw4YEBs3hXSjAhAEdStYCPsu3QNEHewyATCIDwN7DjFAcOsKDQ9AHiyw4V+3XMWfCAHRUETJiAYIGLGphTH6SxuHHn1wEiiLV4VzVmza5hdy5gUkBt24gXtNZNnIMHAVOBH2a9mThs476VI1a8ooDzzhEONEBgIrl0vDIEVP+Icd1xhBMCCn6/LKAB+fKAzwsgu/6whPbv4XMdcCB9ffsCjMABWwQWaGBjBYhF339m3SeADgxEKOGEFErYAQtJ3SQDg4ddMENTIIYIIgVJTSAADQukqOICNHBIVQIwxijjjDBeUBGJAYiI0gQufjcUCEkp0IGECjBQ5EU9SjcUjgcO0ANOSdpGAwIrQMCCUQRu1QIEAhgWpWof4rgVAx1AAEFaHBB2wZeq1VDSXwU0BUELLajJZmouiFbBaBMsUAJfGTjggAYCrFmVBAYkquidAAhnIkodKZYBARgQOkMJCVxwQQK/rVQRiAswypBwk/JAaIgLrvRBiA8kkKJ3jJL/ukEOHXgAlwbHqdeSATqeCACsXwqnAQYEbCCoA8Yy4F9DMzxQV13qXeDsAw9cwCuIHkCwwqOoxSpAoA4QIKe4qSokokHCOQVEiCcMEENoArjw653CeYADBBmEEIKJGlS0IUIXhJBTCB6UaTAC24XQlMAiihnASctGma5FKjUqAEwhAMHRXY5a1MEGxhqbQa8irnAABikMAMEII0ygcLkMXiADVLWReoOIE6i1AQE87+xAZClQJqIOLBwAA0oavMfByAKQ0OmXIVRwA8/iTbBnBRV4oFa4PPNcFFIBnDBCiD0g1QIDGmTwqAp/DUCSoWxaFDKyPGPgGNc7E3DAWqc2/1XdVmzdPMEIRSoQAAUjkPAACXC76CACHngwAgQbHCDC3XV7DRgGXIKogFZqtTBbTEmh1G2PDjaFwOWccU2s3oA5oCyIcwYWAQtDztTAoxbpG0IDwEqnqbVuZpDb1j1rrjMBP0BsUe2OIbUDyfO5IC+HEiRQAQPHc+W68t4XS0DnAnTAgW4kWVTA+tYxZVHwyrXXPfI7Y3CAdcgXu4EGN2WdwmsDYAEGMHCCCCAlAhFI0AkIY6KnqWYBD9AAA0DHmbwRwAGY61kOImMRDAGQLYFBCgxoMgEXtEg5JEmZbg7ANQfgL39dc4AIlOWyCsAAbPoBnIngd5ihHKAFxClA3f8wh4G8YTAGzjsTBl6on5MAxwAIkCATYcM+IsZwK+s7HEoUcD79RGCHtglPBrpoHfaZEYuBKWMA1neyrtlvLSwwUwaKksMAHIBLp7uMDzxguDo6pgA/s1z0QFhH/jTNgWYxgGD8yBkEMRKAIBCAZRBjgAY88pL6AeEAIjnJwxigApgMZRBPcIC0bFKSl6mkKFfZSKER5ZSdzMsnWUnLtUSSIAWAZSotWctaDoAyFxBCbDiZSlD2kpa/FA0CDqBLSvLymKscAAwgxkxiOhOajEQgBQMgggPA5AAcsOZhSvBMbOrnBQd4Aeu2IgJi/SCXkaRNXlbFGHPm0AIWQMEL1CL/AgJ4cJPw+kDjqvKj+dnTPC/IQT7x6YAXwAkwA/hUxcqyJIMeVC3rswEK8IlPfU5RLQdgCgnwUtGLwiYCL0CBDTi6UXzmQATb3IpRLkbSN5n0NShVKEs5+tKYgk0AE7VKSYmDw16iVKULXakFbCDDbRZAAUKaAMyCMlQA9iADGIgpKyOg0Zbmc58hdKVPauqwzhzgZtA7ZgREkNJ82kCQj1FARcZqlooWNTDviolnDsTKlepzAFpdYwEqMlCqGAArICgAA9LCmbwGAaqQhayRFODBUIrgsusMYSQRcAEetiQ8CLAOD741oANxAF7UK6s5GdAAEoQKL7xi2ykrsIIM/9j2thmAgAZwcAEa0EhGC9gd1kZAyM6kqQE7sKhjODA2xIBWhNQTwGsfUhEThYCAJ/ioWpYmAB9cR2V7+gAiq8IrDQygA7zzk6ZKsN7OfuQCKLmhcbnkXecMACYCmEEqgQqCsaFkvCAxgAmaJQAMzI+7MWgSgUBjkQUgyrNBKQFKTBAei9AVKOHRAAW0W6cJ3CCyhQPxDSqgMC+lJkU14FiKzHIS7R7FldS7sKg8JYDOJHMEFIDs2GaAIhXN+Ccn+Ur0KAOB0nKASxD+cYDh24DjJXOMW4EOgJXsqQkoYIr8gQDk/hcADGzHxFQGylB44ORvAjGZ+g0zVUkXQjMfRYUHAsijmluCFR3cD6LfxBJlPvCvOe8KvgJI8FrczBUn+vknLtjO3vYDExYMCHDNPfRPPpRVRheYBSzAX6Ql3RK+MBOj6LEIiQawaU6vJE+55XJs4iSAFVQJvQIw9U8qkjK2xEklWEGJrF1iABeMIHKRq4hKMFWjXfNaRCM1NnkfrJEpRyQgACH5BAkIAAAALBoAGgBwAFwAh/n9+PTGBQIBAv7UCbx6Eea4CtLXz8icBzY5MJOZkqOpopFzAxgWCYRsGc6LFyslClFYVdvh3G1YEvlGSvnQKJWISLS6tCgbALCDE2FKBFVBB/TVTKycU85/EH9iD2VqZDwwCLCTHNiwFSAmJvCpJks4BG90cfPONj9GRlNQNUlGLM6oBsDFve1NN/iMNoCEetzDT3uBf8DGxYmOjLmjRqCkmm9oSMtqEPtaR2dcMol0McSrP8u5Zc+2R6Z6J6SdcuXr55h8Tf///gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAj/AF+gQGECgMGDCBMqXMiwocOHECNKPIhAgIARAAxE2BhhosePIEN+TCGgwgOLKBGIXMmypUcVAmhIuPCgZk0EOBGgQMDCpc+fIiEIOEAhwIABATYsQInyhQEZLDoCnUpVIYqhRQNo1SpCRAGvIZh+qEq26tUQW9MeXStCg1sNKUx8+ADBQNm7KyOYEGADadq/RtdKYKoAr2GQCgRI8Au4sYgDB1ZUYArhsGWHCfgybvyXwtoeFwQwYIAgwYsZl1MfzLyYs2vAFDCgtKv6cua+r3NvLWBSAO3ah2so3qzb9YYSAqQCN3ybePHGx30vP5w4RYHnrikceIDAhPLpd2UI/7gAA3tjCmELgrcs4EF5853Djl1vOEL79/C3DjggQD39u/aBsMFaBBZoIGMFyDbff2XZJ4AODUQo4YQUSuiBCFo9cIEMDBpmQQxMhShiiBUgxYAANSSg4ooJ1NDhVArEKOOMNMZoQUUlBjAiUy+CJxQHSC3gwYQLLGDDRT1OJ1SOBw6wwwUqJalaDQikIMEKRRGo1QmDFSalaiDmqFUDHnggAVoneCCABV+qNkNJfhXAlAQnpLlmm6m9INpooyXAwl4ZOOCABndSFYEBiCaKJwCZjbZnR4llQAAGhMbAggIWWKDAbytVFGICizKUmaQ/ECrigit9ICIECqj43aKjEv9wgwclvKUBcv6xZMCOKALw6peZadABAR0I6kCxDfTnUAwQ0EWXehY0CwEEFuwaYgkSpHCiAKjBKkCgDiSLkgQECICqQiMalFlTQIgYwgAwhCbAC77imVkJNniQwQgjnKhBRRwiZAFp/GoggZllIsDdCEyN4CmJjJ2kLLBMRZkZTCMAwZFdjVrkQQfF3uDAYLyKmMIBGIgwgAQggMAAw+cyaIEMBrBA26g5jMhAWsMS4DMBDkQm2Y46rHAADShp8N4GGVikwq9JjnBBDj6PNx4DF1xQQloO+IyBzwesFUAIIIi4w1EnNKBBBtuqMECWJLGJp0XF1v01Bo11TezXB6j/ZSpT1mm1Vs7tFblAABWAgMC0cvfoIAIllACCBB0ccB1gen9NQN9pYUAyUwtkldYJsllEA1Iodeu4iAiQUIBzAWQO9l/hikgnbCIMKcEDjqLE7wMjQL1cptW+mQLsWundM+dbDeuDxBbd3thRPJRs7gv0dhiBAhc0gHzsXs/ONbEEfO7BBrqRZFEB1xUAw1IWCQ9ce98n/3Pll2+lfAca1KQ1hq4ZwAowgIF3ecYzCQqBmizCqdokAAIaaIBuega0/OnvZ8QKmkVWUD8t/eUoNKDJBV7gouWQRGW6OYDeHGBB+2HQASRI1ssucLr6ZccoJ5IfXoRygBMUpwBey9uk/3rmgADAAHpnwkALzXMS4BgAARFcomvYJ8Wuaa6CAWAf4lCyAPTlhwI5rI14MuBFKpoxf0tsXxYLgLKfYYB5RtmBBCSQAaLkRysHGIzqLMMDDRzujpxhY9BIMD2xAXID/EFBA+9igMAA8jVxemRuBsABAVTmMAa4gCQ3CUixUdKSljHAAzhJSuwUIAQHCMHrKnlJw2SylLCE5GQsEjZWhlKTsczlBytJEJXZEpOj1KUwjVJJCwghABT4pSuDOcxcDmAypKklKDGJy2bGcgA0kJg0W4kXUVpTkhQI519IcACYHGADysQLC5j5zfy44AAuIORWSPA1H6xyNnhRVWvamf+fCUygBS5ICwkIwEFiyusDjavKj2zIz7RQwAU3+Kc/HeCCAfiwhQPwVJTIsiSGNlQrBcBBC/zpT4BK0SgHWAoK7tLRj+bmoS3AAUlH6s8bkEB0DtWRClgKJ5e+5qERnSlJbYpTwaFuowrtaXGO8k2IklSm/sQBDAEjgiI1gAExA0pLJ7mDDGCgqMIUKUn/GVDAPBMlCU2qmF5zgJxJr5kDIIELRhrTA8iTqguoSE94WiKmciZeMQlMk2JJAZEC9Hvsq0hap2KAq3CgAA1Ay19DEwTDWXYBDShSQUtJgs7e1ayVRMBigbIrBFznB98a0IE2IC/rrZWfDXgACkDFSAH/uO2TF0hBBnbL291qwAYWqEGNZpQA3mUNBIY0jgce0AOPpmUDZTuMeBAAQusJgLYPqQifQsDdk2qFaQLgAXZWdgGsLrIqu9LAADywreuyIFPvtcB7dbiQxFgESMYZjHifk1GLxCCUAkAAB8qGT58YwATMEgAGkAdeGDSJQKCxSAIORd+fsAAlJhCPRfYKFPFooAKcSRMDcnDZzF42Bxdg2GjxoqIZcCwBe5zKSU56VusWKlQtqUgBwGqUyYCgAoYrWwxStCIc++QkK+DMWSWgWvBW2MgfMYAFxuOcs5Lxu8g5L5RzzIAFoFA/eVQcADHAHS9tWasCwO8HzenDs/73j8xoPp1Z2WwUHXALzkC5ig4st2as9NhcAcNzS6RsEQerhc5baaKgfRIDxdlRcDBZwYAEF91FM1rBohsATDCwghVcrtKWbslewpaWU6Kkr6AO9Ur0lAEJABCZchJACqzEXgao2icVUdla5LTSq6Dk1i4xwAtAELnIVUQll9KUmYG9EmuFaKXMpopGpn2olgQEADs="


# ============================================================
# TEMA VISUAL — inspirado en la paleta verde oscuro / dorado
# ============================================================
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500&display=swap');

:root {
    --atlas-gold: #d3a15a;
    --atlas-gold-soft: #c9974a;
    --atlas-text: #f2f1ea;
    --atlas-text-dim: #a3ada4;
    --atlas-card-bg: rgba(255,255,255,0.035);
    --atlas-card-border: rgba(211,161,90,0.28);
}

#MainMenu, footer, header {visibility: hidden;}

html, body, [class*="css"] {
    font-family: 'Inter', sans-serif;
}

.stApp {
    background: radial-gradient(circle at 50% 0%, #16261c 0%, #0b140d 45%, #050805 100%);
    background-attachment: fixed;
}

.block-container {
    max-width: 760px;
    padding-top: 2.2rem;
}

/* Emblema GIF */
.atlas-emblem-wrap {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 0.6rem;
}

.atlas-gif {
    width: 176px;
    height: 176px;
    object-fit: contain;
    display: block;
    animation: atlas-float 2.4s ease-in-out infinite;
    transform-origin: center bottom;
}

@keyframes atlas-float {
    0%, 100% { transform: translateY(0) rotate(-3deg); }
    50% { transform: translateY(-9px) rotate(3deg); }
}

/* Título principal */
h1 {
    font-family: 'Playfair Display', Georgia, serif !important;
    color: var(--atlas-text) !important;
    font-weight: 800 !important;
    text-align: center;
    letter-spacing: 0.2px;
}

/* Texto descriptivo bajo el título */
div[data-testid="stMarkdownContainer"] p {
    color: var(--atlas-text-dim);
    text-align: center;
    font-size: 15.5px;
}

div[data-testid="stMarkdownContainer"] strong {
    color: var(--atlas-gold);
}

/* Zona de carga de archivos */
[data-testid="stFileUploaderDropzone"] {
    background: var(--atlas-card-bg) !important;
    border: 1.5px dashed var(--atlas-card-border) !important;
    border-radius: 16px !important;
}

[data-testid="stFileUploaderDropzoneInstructions"] * {
    color: var(--atlas-text-dim) !important;
}

[data-testid="stFileUploaderDropzone"] button {
    background: transparent !important;
    border: 1px solid var(--atlas-gold) !important;
    color: var(--atlas-gold) !important;
    border-radius: 8px !important;
}

[data-testid="stFileUploaderFile"] {
    background: var(--atlas-card-bg) !important;
    border-radius: 10px !important;
}

[data-testid="stFileUploaderFile"] * {
    color: var(--atlas-text) !important;
}

/* Botones principales */
.stButton > button, .stDownloadButton > button {
    background: linear-gradient(135deg, var(--atlas-gold), #a97a34) !important;
    color: #1a1206 !important;
    border: none !important;
    border-radius: 10px !important;
    font-weight: 600 !important;
    font-family: 'Inter', sans-serif !important;
    padding: 0.55rem 1.1rem !important;
    transition: filter 0.2s ease, box-shadow 0.2s ease;
}

.stButton > button:hover, .stDownloadButton > button:hover {
    filter: brightness(1.08);
    box-shadow: 0 0 16px rgba(211,161,90,0.35);
}

/* Spinner */
[data-testid="stSpinner"] * {
    color: var(--atlas-text-dim) !important;
}

/* Alertas */
.stAlert {
    background: var(--atlas-card-bg) !important;
    border: 1px solid var(--atlas-card-border) !important;
    border-radius: 12px !important;
}

.stAlert * {
    color: var(--atlas-text) !important;
}

/* Divisor */
hr {
    border-color: rgba(211,161,90,0.2) !important;
}

/* Pie de página */
.atlas-footer-box {
    border: 1px solid var(--atlas-card-border);
    background: rgba(211,161,90,0.05);
    border-radius: 14px;
    padding: 12px 18px;
    margin-top: 1.2rem;
}

.atlas-footer-box p {
    color: var(--atlas-text-dim) !important;
    font-family: 'JetBrains Mono', monospace !important;
    font-size: 12.5px !important;
    text-align: center;
    margin: 0 !important;
}
</style>
""", unsafe_allow_html=True)

# --- EMBLEMA ANIMADO ---
st.markdown(
    f"""
    <div class="atlas-emblem-wrap">
        <img
            class="atlas-gif"
            src="data:image/gif;base64,{GIF_BASE64}"
            alt="Pikachu animado"
        >
    </div>
    """,
    unsafe_allow_html=True
)

st.title("🏗️ Generador LISP para AutoCAD")
st.markdown(
    "Sube tus archivos Excel. La plataforma extraerá las coordenadas "
    "y generará automáticamente un único archivo **.lsp**."
)

# Casilla para arrastrar archivos
archivos_subidos = st.file_uploader(
    "Arrastra tus archivos Excel aquí",
    type=["xlsx", "xls"],
    accept_multiple_files=True
)

if archivos_subidos:
    if st.button("🚀 Generar Archivo LISP"):
        with st.spinner("Procesando vértices en orden ascendente..."):
            codigo_lisp, cantidad = procesar_excels_a_lisp(archivos_subidos)

            if cantidad > 0:
                st.success(
                    f"✅ ¡Perfecto! Se procesaron {cantidad} predios sin errores."
                )

                st.download_button(
                    label="⬇️ Descargar archivo DIBUJAR_PREDIOS.lsp",
                    data=codigo_lisp,
                    file_name="DIBUJAR_PREDIOS.lsp",
                    mime="text/plain"
                )
            else:
                st.error(
                    "No se pudo extraer coordenadas válidas de los archivos."
                )

# --- PIE DE PÁGINA ---
st.markdown("---")
st.markdown(
    "<div class='atlas-footer-box'>"
    "<p>© 2026. Sitio web creado por Emerson Gutierrez Vega.</p>"
    "</div>",
    unsafe_allow_html=True
)
